# Generated by Django 3.2.7 on 2021-09-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contrato', models.CharField(max_length=50)),
                ('id_tarea', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('lote', models.CharField(max_length=20)),
                ('parte', models.CharField(max_length=20)),
                ('cantIns', models.PositiveIntegerField()),
                ('cantRech', models.PositiveIntegerField()),
                ('defecto', models.CharField(max_length=20)),
                ('cantRet', models.PositiveIntegerField()),
                ('cantAcep', models.PositiveIntegerField()),
            ],
        ),
    ]
